blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community Server
    url: https://discord.gg/4H2v6UwjmY
    about: Join our Discord server to ask questions, chat, or get instant support from the Ground Zero community.
  - name: 👥 Facebook Community Group
    url: https://www.facebook.com/groups/groundzerocommunity/
    about: Ask questions, share projects, and collaborate on our Facebook Group.
